use regex::Regex;

pub struct BoilerplateDetector {
    patterns: Vec<CompiledPattern>,
}

struct CompiledPattern {
    regex: Regex,
    confidence: f64,
}

impl BoilerplateDetector {
    pub fn new() -> Self {
        Self::with_patterns(default_patterns())
    }
    
    pub fn with_patterns(patterns: Vec<(&str, &str, f64)>) -> Self {
        let compiled: Vec<CompiledPattern> = patterns
            .into_iter()
            .filter_map(|(_category, pattern, confidence)| {
                Regex::new(pattern).ok().map(|regex| CompiledPattern {
                    regex,
                    confidence,
                })
            })
            .collect();
        
        Self { patterns: compiled }
    }
    
    pub fn with_additional_patterns(mut self, patterns: &[Regex]) -> Self {
        for regex in patterns {
            self.patterns.push(CompiledPattern {
                regex: regex.clone(),
                confidence: 0.90,
            });
        }
        self
    }
    
    pub fn detect(&self, text: &str) -> f64 {
        if text.trim().is_empty() {
            return 0.0;
        }
        
        let mut max_confidence = 0.0;
        
        for pattern in &self.patterns {
            if pattern.regex.is_match(text)
                && pattern.confidence > max_confidence {
                    max_confidence = pattern.confidence;
                }
        }
        
        max_confidence
    }
    
    #[allow(dead_code)]
    pub fn is_boilerplate(&self, text: &str, threshold: f64) -> bool {
        self.detect(text) >= threshold
    }
}

impl Default for BoilerplateDetector {
    fn default() -> Self {
        Self::new()
    }
}

pub fn default_patterns() -> Vec<(&'static str, &'static str, f64)> {
    vec![
        ("license", r"(?i)^(MIT License|Apache License|GNU|BSD)", 0.95),
        ("copyright", r"(?i)^(Copyright \(c\)|©)", 0.90),
        ("generated", r"(?i)^(Auto-generated|DO NOT EDIT|Generated by)", 0.95),
        ("disclaimer", r"(?i)^(THE SOFTWARE IS PROVIDED|WITHOUT WARRANTY)", 0.90),
        ("separator", r"^[-=]{20,}$", 0.85),
        ("import_block", r"(?m)^(import |from .+ import |require\(|use |#include )", 0.75),
        ("license_full", r"(?is)permission is hereby granted.*the software", 0.95),
        ("all_rights", r"(?i)all rights reserved", 0.85),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_mit_license() {
        let detector = BoilerplateDetector::new();
        let confidence = detector.detect("MIT License\n\nCopyright (c) 2024");
        assert!(confidence >= 0.90);
    }

    #[test]
    fn test_copyright_notice() {
        let detector = BoilerplateDetector::new();
        let confidence = detector.detect("Copyright (c) 2024 Katie");
        assert!(confidence >= 0.90);
    }

    #[test]
    fn test_auto_generated() {
        let detector = BoilerplateDetector::new();
        let confidence = detector.detect("Auto-generated file, DO NOT EDIT");
        assert!(confidence >= 0.95);
    }

    #[test]
    fn test_normal_text_not_detected() {
        let detector = BoilerplateDetector::new();
        let confidence = detector.detect("This is normal text about programming.");
        assert_eq!(confidence, 0.0);
    }

    #[test]
    fn test_partial_match() {
        let detector = BoilerplateDetector::new();
        // "license" in middle of text shouldn't match pattern that requires start
        let confidence = detector.detect("I have a license to code");
        assert_eq!(confidence, 0.0);
    }

    #[test]
    fn test_case_insensitive() {
        let detector = BoilerplateDetector::new();
        let conf1 = detector.detect("MIT LICENSE");
        let conf2 = detector.detect("mit license");
        assert!(conf1 >= 0.90);
        assert!(conf2 >= 0.90);
    }

    #[test]
    fn test_highest_confidence() {
        let detector = BoilerplateDetector::new();
        // Both license and copyright patterns should match, license is higher
        let confidence = detector.detect("MIT License\nCopyright (c) 2024");
        assert!(confidence >= 0.95);
    }

    #[test]
    fn test_custom_patterns() {
        let custom = Regex::new(r"(?i)^TODO:").unwrap();
        let detector = BoilerplateDetector::new().with_additional_patterns(&[custom]);
        let confidence = detector.detect("TODO: fix this later");
        assert!(confidence >= 0.90);
    }

    #[test]
    fn test_empty_segment() {
        let detector = BoilerplateDetector::new();
        assert_eq!(detector.detect(""), 0.0);
        assert_eq!(detector.detect("   "), 0.0);
    }

    #[test]
    fn test_is_boilerplate() {
        let detector = BoilerplateDetector::new();
        assert!(detector.is_boilerplate("MIT License", 0.90));
        assert!(!detector.is_boilerplate("Regular text", 0.90));
    }

    #[test]
    fn test_separator_line() {
        let detector = BoilerplateDetector::new();
        let confidence = detector.detect("--------------------");
        assert!(confidence >= 0.85);
    }
}
